name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v2

    # Étape 2 : Installer les dépendances PHP
      - name: Install PHP dependencies
        run: composer install
    

      - name: Build backend project
        run: |
        
          composer run build 

     # Étape 5 : Exécuter les tests PHP
      - name: Run PHP tests
        run: vendor/bin/phpunit 


      - name: Package application
        run: |
           zip -r application.zip . -x "node_modules/*" "vendor/*

      - name: Build Docker image
        run: 
         docker build -t my-app:latest .